### ISSUE TITLE
Update `crr()` to handle categorical covariates

### ISSUE THREAD

**Issue by ddsjoberg** [MSKCC-Epi-Bio/tidycmprsk#15]
I think we need to update how the categorical covariates are passed to `cmprsk::crr()`....we're getting errors.

``` r
library(tidycmprsk)

crr(Surv(ttdeath, death_cr) ~ factor(response), trial)
#> 7 cases omitted due to missing values
#> Error in solve.default(h, z[[2]]): system is computationally singular: reciprocal condition number = 3.54585e-17
```

<sup>Created on 2021-10-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dpmoriarity3** [comment]
Hello,

Error code: Error in solve.default(h, z[[2]]) : 
  system is computationally singular: reciprocal condition number = 3.69382e-17

I am using CRR() with a factor covariate (tried creating 2 ways:  "as.factor()" and "factor()")and this issue is coming up (seemed related to the OP). Does not exist when using dichotomous or continuous variables. All 4 factor categories are represented in the data if that matters.

Tried to create a reproducible sample (sorry, am new at this) but it didn't reproduce the error. So, it seems like user error somehow but I am not finding anything else with this issue online to trouble shoot.

 I'm happy to share data and code if it is helpful. Please let me know if Github is an inappropriate location for this query.
